### ISSUE TITLE
[roadmap] todo list

### ISSUE THREAD

**Issue by penguin1333** [teamprova/Dungeontest#2]
##### This is a todo list for Dungeontest, but some other enhancements and bugs in the issues should not be ignored either:
- [x] 1.) Entity moving towards another entity, method, for the API.
- [x] 2.) Input Handling for the API.
- [x] 3.) Sending updates to mods.
- [ ] 4.) Inventory mod
- [ ] 5.) GUI mods
- [ ] 6.) Convert mini-map to mod
- [ ] 7.) Method to change an entity/blocks texture.
- [ ] 8.) Glass (transparent blocks)
- [ ] 9.) Player skins
- [ ] 10.) Player back sides (so we can see where players are looking)
- [ ] 11.) Fix when you regenerate levels a few times, and get intense lag. (Threading issue?)
- [x] 12.) Updating entities through mods
- [ ] 13.) Moving player controls to a mod file
- [ ] 14.) Drawing text to the canvas texture (useful for name tags)
- [ ] 15.) Name tags (displays only when hovering?)
- [ ] 16.) More entities!
- [ ] 17.) Colored lighting?
- [ ] 18.) Convert dungeon generation to mod
- [ ] 19.) Interaction with blocks/entities (player clicking something)
- [x] 20.) Making a class specifically for writing the mod API (API.cs?)
- [ ] 21.) Code cleanup
- [ ] 22.) Screenshots!
- [ ] 23.) Pause menu
- [ ] 24.) Sounds! (with API)
- [ ] 25.) Music?
- [ ] 26.) Ability to see held item (on both others and self)
- [ ] 27.) Health!
- [ ] 28.) Mana!
- [ ] 29.) Items (wands, swords, bows, daggers each with their own advantages and disadvantages)
- [ ] 30.) Performance improvements
- [ ] 31.) Gold + Shops
- [ ] 32.) Different room types
- [ ] 33.) Mods from server copied to a folder generated for the server
- [ ] 34.) Updated design?
- [ ] 35.) Multiple dungeons
- [ ] 36.) Goals for the player
- [ ] 37.) Bosses unique from the other entities
- [ ] 38.) Achievements
- [ ] 39.) Settings (fov, mouse sensitivity, etc)
- [ ] 40.) Find a good speed for the player to move at.
- [ ] 41.) Make sure that game content/gameplay features are written in Lua, and engine stuff is written in C#.
- [ ] 42.) Allow ClaimID() to have entity names
- [ ] 43.) Complete everything in the issues list!
- [ ] 44.) Allowing mods to create their own protocols to send data back and forth
- [ ] 45.) Ability to change the sprite of something that already exists
- [ ] 46.) Discuss and create milestones
- [ ] 47.) A UseHeldItem() method and UsedItem(Entity e) event for mods
- [ ] 48.) A bump method to push entities around (from hitting or otherwise)
- [ ] 49.) Add Connected() event for client mods
- [ ] 50.) Create a way for mods to know if this is a client, server, or singleplayer game

**Comment by penguin1333** [comment]
2.) Is complete, but 3.) needs to be complete for it to actually be effective.

**Comment by ArthurCose** [comment]
3.) Updates to mods are handled in API.cs under class ModHandler in the RunEvent(string methodName, params object[] args) method.

12.) Entities have a MoveTo(int x, int y) method now.

20.) API code is being put in the API.cs file now. (Excluding things like Input.cs and Entity.cs)

**Comment by ArthurCose** [comment]
1.) Added new methods Chase(Entity e, float speed) and Evade(Entity e, float speed)
ex. myEntity.Evade(otherEntity, 2);
